translate
WildCodeSchool/quest-java-oop3 pull request #2
Opened 2019-10-29 22:46 UTC by florianpdf

2019-10-30 07:49 UTC, bastienapp requested changes

2019-10-30 07:49 UTC, bastienwcs commented on Bird.java
> +    // accessors and mutators
getters and setters

2019-11-21 17:03 UTC, bhubr approved these changes

2019-11-21 17:06 UTC, bastienapp approved these changes

2019-11-21 17:06 UTC, merged